# Generated by Django 5.2 on 2025-07-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyunit',
            name='is_negative_allowed',
            field=models.BooleanField(default=False, verbose_name='Валюта может уходить в минус'),
        ),
    ]
