# Generated by Django 5.2.9 on 2026-01-09 20:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_currencyunit_is_negative_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkingaccount',
            name='currency_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checking_accounts', to='currencies.currencyunit', verbose_name='Игровая валюта'),
        ),
        migrations.AlterField(
            model_name='exchangerule',
            name='forward_rate',
            field=models.DecimalField(decimal_places=4, help_text='За какое количество валюты 1 будет выдана одна единицу валюты 2', max_digits=13, verbose_name='Прямой курс'),
        ),
        migrations.AlterField(
            model_name='exchangerule',
            name='reverse_rate',
            field=models.DecimalField(decimal_places=4, help_text='Какое количество валюты 1 будет выдано за одну единицу валюты 2', max_digits=13, verbose_name='Обратный курс'),
        ),
        migrations.AlterField(
            model_name='holder',
            name='holder_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Внешний уникальный ID'),
        ),
        migrations.AlterField(
            model_name='transferrule',
            name='fee_percent',
            field=models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Комиссия за обмен (%)'),
        ),
        migrations.AlterField(
            model_name='transferrule',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_rules', to='currencies.currencyunit', verbose_name='Игровая валюта'),
        ),
    ]
