# Generated by Django 5.1.7 on 2025-04-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyunit',
            name='measurement',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='currencyunit',
            name='symbol',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
