# Generated by Django 5.1.7 on 2025-03-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holder',
            name='info',
            field=models.JSONField(default=dict),
        ),
    ]
