# Generated by Django 5.1.7 on 2025-03-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='enabled',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
