# Generated by Django 5.1.7 on 2025-03-23 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_holder_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurrencyTransaction',
            new_name='AdjustmentTransaction',
        ),
    ]
