# Generated by Django 5.1.7 on 2025-03-23 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_rename_currencytransaction_adjustmenttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustmenttransaction',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='currencies.service'),
        ),
        migrations.AlterField(
            model_name='exchangetransaction',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='currencies.service'),
        ),
        migrations.AlterField(
            model_name='transfertransaction',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='currencies.service'),
        ),
    ]
