# Generated by Django 5.1.7 on 2025-03-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0004_alter_adjustmenttransaction_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
