# Generated by Django 5.1.7 on 2025-03-26 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0005_alter_holder_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustmenttransaction',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=13),
        ),
        migrations.AlterField(
            model_name='checkingaccount',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=13),
        ),
        migrations.AlterField(
            model_name='exchangerule',
            name='forward_rate',
            field=models.DecimalField(decimal_places=4, max_digits=13),
        ),
        migrations.AlterField(
            model_name='exchangerule',
            name='min_first_amount',
            field=models.DecimalField(decimal_places=4, max_digits=13),
        ),
        migrations.AlterField(
            model_name='exchangerule',
            name='min_second_amount',
            field=models.DecimalField(decimal_places=4, max_digits=13),
        ),
        migrations.AlterField(
            model_name='exchangerule',
            name='reverse_rate',
            field=models.DecimalField(decimal_places=4, max_digits=13),
        ),
        migrations.AlterField(
            model_name='exchangetransaction',
            name='from_amount',
            field=models.DecimalField(decimal_places=4, max_digits=13),
        ),
        migrations.AlterField(
            model_name='exchangetransaction',
            name='to_amount',
            field=models.DecimalField(decimal_places=4, max_digits=13),
        ),
        migrations.AlterField(
            model_name='transfertransaction',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=13),
        ),
        migrations.CreateModel(
            name='TransferRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('fee_part', models.DecimalField(decimal_places=4, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.currencyunit')),
            ],
            options={
                'verbose_name': 'Правило перевода валюты',
                'verbose_name_plural': 'Правила перевода валют',
            },
        ),
    ]
