# Generated by Django 5.1.7 on 2025-03-26 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0006_alter_adjustmenttransaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangetransaction',
            name='from_amount',
            field=models.DecimalField(decimal_places=4, max_digits=13, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='exchangetransaction',
            name='to_amount',
            field=models.DecimalField(decimal_places=4, max_digits=13, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transfertransaction',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=13, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
