# Generated by Django 5.1.7 on 2025-03-26 18:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0007_alter_exchangetransaction_from_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfertransaction',
            old_name='amount',
            new_name='from_amount',
        ),
        migrations.RemoveField(
            model_name='transferrule',
            name='fee_part',
        ),
        migrations.AddField(
            model_name='transferrule',
            name='fee_percent',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferrule',
            name='min_from_amount',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=13, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfertransaction',
            name='to_amount',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=13, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfertransaction',
            name='transfer_rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='currencies.transferrule'),
        ),
    ]
