apiUrl = "https://api.telegram.org"
token = ""
admins = [""]

[backup]
chatIDs = [""]
dir = "/app/backups"
interval = "10s"

[postgres]
dbName = "postgres"
host = "db"
password = "dev"
port = "5432"
user = "postgres"
