
name: gaming-billing

services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - static_value:/var/html/static
    group_add:
      - 110 # для чтения статики из сервиса playtime
    depends_on:
      - gaming-billing
    networks:
      - to-wan-network
    configs:
      - source: nginx
        target: /etc/nginx/conf.d/default.conf

  gaming-billing-migrations:
    build: ../gaming_billing_service/
    command: ["./migrations.sh"]
    stop_signal: SIGINT
    depends_on:
      db:
        condition: service_healthy
    networks:
      - only-lan-network
    configs:
      - source: gaming-billing
        target: /app/config.toml

  gaming-billing:
    build: ../gaming_billing_service/
    command: "gunicorn settings.wsgi:application --bind 0:8000"
    stop_signal: SIGINT
    restart: always
    volumes:
      - static_value:/app/static
    group_add:
      - 110
    depends_on:
      gaming-billing-migrations:
        condition: service_completed_successfully
    networks:
      - only-lan-network
      - to-wan-network
    configs:
      - source: gaming-billing
        target: /app/config.toml

  # gaming-billing-cron:
  #   build: ../gaming_billing_service/
  #   command: ["python3", "manage.py", "cronloop", "-s", "300"]
  #   stop_signal: SIGINT
  #   restart: always
  #   depends_on:
  #     - gaming-billing
  #   networks:
  #     - only-lan-network
  #   configs:
  #     - source: gaming-billing
  #       target: /app/config.toml

  db:
    image: postgres:15.4-bookworm
    restart: always
    volumes:
      - postgres_value:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - only-lan-network
    env_file:
      - ./configs/postgres/postgres.env

volumes:
  postgres_value:
  static_value:

networks:
  to-wan-network:
  only-lan-network:

configs:
  gaming-billing:
    file: ./configs/gaming_billing/config.toml
  nginx:
    file: ./configs/nginx/default.conf