# Generated by Django 5.1.7 on 2025-03-29 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=512)),
                ('is_battlemetrics', models.BooleanField()),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hmac', to='currencies.currencyservice')),
            ],
            options={
                'verbose_name': 'Доступ сервиса',
                'verbose_name_plural': 'Доступ сервиса',
            },
        ),
    ]
