# Generated by Django 5.1.7 on 2025-03-26 19:51

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicehmac',
            name='permissions',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
    ]
