# Generated by Django 5.1.7 on 2025-03-30 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
        ('currencies_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceAuth',
            new_name='CurrencyServiceAuth',
        ),
    ]
